//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by nwnexplorer.rc
//
#define IDR_NWNEXPLORER                 1
#define IDR_POPUPS                      101
#define IDR_TOOLBAR_POPUP               102
#define IDR_PAL_TATTOO01                103
#define IDR_PAL_ARMOR01                 104
#define IDR_PAL_ARMOR02                 105
#define IDR_PAL_CLOTH01                 106
#define IDR_PAL_HAIR01                  107
#define IDR_PAL_LEATHER01               108
#define IDR_PAL_SKIN01                  109
#define IDD_SOUND                       163
#define IDD_NWN                         166
#define IDD_MODEL_COLOR                 169
#define IDI_PITCH_FORWARD               170
#define IDI_PITCH_BACKWARD              171
#define ID_FILE_EXPORT                  171
#define IDI_YAW_RIGHT                   172
#define ID_Menu                         172
#define IDI_YAW_LEFT                    173
#define ID_RESOURCES_EXPORT             173
#define IDI_ROLL_RIGHT                  174
#define ID_RESOURCES_EXPORTTEXT         174
#define IDI_ROLL_LEFT                   175
#define IDI_ZOOM_OUT                    176
#define IDI_ZOOM_IN                     177
#define IDI_MOVE_LEFT                   178
#define IDI_MOVE_RIGHT                  179
#define IDI_MOVE_UP                     180
#define IDI_MOVE_UP1                    181
#define IDI_MOVE_DOWN                   181
#define IDB_TOOLBAR_16_256COLOR         401
#define IDB_TOOLBAR_24_256COLOR         402
#define IDB_TOOLBAR_16_16COLOR          403
#define IDB_TOOLBAR_24_16COLOR          404
#define IDB_COLOR_ARMOR                 405
#define IDB_COLOR_LEATHER               406
#define IDB_COLOR_CLOTH                 407
#define IDB_COLOR_HAIR                  408
#define IDB_COLOR_SKIN                  409
#define IDB_COLOR_TATTOO                410
#define IDD_ABOUTBOX                    501
#define IDD_TBCUSTOMIZE                 502
#define IDD_MODEL_POS                   503
#define IDC_PLAY                        1055
#define IDC_LOAD_NWN_FROM               1056
#define IDC_NWN_DIRECTORY_BROWSE        1058
#define IDC_MODEL_ARMOR1                1059
#define IDC_MODEL_ARMOR2                1060
#define IDC_MODEL_CLOTH1                1061
#define IDC_MODEL_CLOTH2                1062
#define IDC_MODEL_LEATHER1              1063
#define IDC_MODEL_LEATHER2              1064
#define IDC_MODEL_HAIR                  1065
#define IDC_MODEL_PITCH_FORWARD         1065
#define IDC_MODEL_SKIN                  1066
#define IDC_MODEL_PITCH_BACKWARD        1066
#define IDC_MODEL_TATTOO1               1067
#define IDC_MODEL_YAW_LEFT              1067
#define IDC_MODEL_TATTOO2               1068
#define IDC_MODEL_YAW_RIGHT             1068
#define IDC_MODEL_ROLL_LEFT             1069
#define IDC_MODEL_ROLL_RIGHT            1070
#define IDC_MODEL_ZOOM_IN               1071
#define IDC_MODEL_ZOOM_OUT              1072
#define IDC_MODEL_MOVE_LEFT             1073
#define IDC_MODEL_MOVE_RIGHT            1074
#define IDC_MODEL_MOVE_UP               1075
#define IDC_MODEL_MOVE_DOWN             1076
#define IDC_TBCUSTOMIZE_TEXT_OPTIONS    4096
#define IDC_TBCUSTOMIZE_ICON_OPTIONS    4097
#define IDC_EXP_TREEVIEW                5000
#define IDC_EXP_CONTENT                 5001
#define IDC_NWN_DIRECTORY               5001
#define IDC_EXP_TABSBOTTOM              5002
#define IDC_EXP_TABSTOP                 5003
#define IDC_EXP_HEADER                  5004
#define IDS_ERR_MAIN_WINDOW             10001
#define IDS_ERR_IMAGE_LOAD              10002
#define IDS_ERR_NOWAVE                  10003
#define IDS_ERR_NO_FMOD                 10004
#define IDS_ERR_FMOD_STREAM             10005
#define IDS_ERR_RESOURCE_OPEN           10006
#define IDS_ERR_NWN_OPEN                10007
#define IDS_ERR_OPEN                    10008
#define IDS_ERR_UNK_FILE                10009
#define IDS_ERR_NO_DIRECTORY            10010
#define IDS_ERR_INV_DIRECTORY           10011
#define IDS_ERR_NO_DIALOGTLK            10012
#define IDS_ERR_EXPORT                  10013
#define IDS_BINARY                      11000
#define IDS_TEXT                        11001
#define IDS_IMAGE                       11002
#define IDS_AUDIO                       11003
#define IDS_SOUND_SET                   11004
#define IDS_SOUND_SET_SOUND             11005
#define IDS_SOUND_SET_SOUND_HEADER      11006
#define IDS_SOUND_SET_SOUND_OTHER       11007
#define IDS_HIERARCHY                   11008
#define IDS_HIERARCHY_RAW               11009
#define IDS_MODEL_RAW                   11010
#define IDS_MODEL                       11011
#define IDS_MODEL_RAW_HIER              11012
#define IDS_MODEL_ASCII                 11013
#define IDS_MODEL_ASCII_HIER            11014
#define IDS_SCRIPT_RAW                  11015
#define IDS_MAIN_KEY                    11016
#define IDS_PATCH_KEY                   11017
#define IDS_USER_MODULES                11018
#define IDS_GAME_MODULES                11019
#define IDS_HAK                         11020
#define IDS_TEXTURE_PACKS               11021
#define IDS_OVERRIDE                    11022
#define IDS_AMBIENT                     11023
#define IDS_DM_VAULT                    11024
#define IDS_LOCAL_VAULT                 11025
#define IDS_SERVER_VAULT                11026
#define IDS_MUSIC                       11027
#define IDS_ITP                         11028
#define IDS_XP1_KEY                     11029
#define IDS_XP1_PATCH_KEY               11030
#define IDS_TBCUSTOMIZE_SMALL_ICONS     12301
#define IDS_TBCUSTOMIZE_LARGE_ICONS     12302
#define IDS_TBCUSTOMIZE_BOTTOM_LABELS   12303
#define IDS_TBCUSTOMIZE_NO_LABELS       12304
#define IDS_TBCUSTOMIZE_RIGHT_LABELS    12305
#define IDS_RESCLASS_FIRST              13001
#define IDS_RESCLASS_MISC               13001
#define IDS_RESCLASS_SOUND              13002
#define IDS_RESCLASS_TEXTURE            13003
#define IDS_RESCLASS_GAMEDATA           13004
#define IDS_RESCLASS_TEXTURE_INFO       13005
#define IDS_RESCLASS_INI                13006
#define IDS_RESCLASS_IMAGE              13007
#define IDS_RESCLASS_MODEL              13008
#define IDS_RESCLASS_UI                 13009
#define IDS_RESCLASS_SCRIPT             13010
#define IDS_RESCLASS_CSCRIPT            13011
#define IDS_RESCLASS_DIALOG             13012
#define IDS_RESCLASS_BLUEPRINT_PALETTE  13013
#define IDS_RESCLASS_BP_WAYPOINT        13014
#define IDS_RESCLASS_BP_TRIGGER         13015
#define IDS_RESCLASS_BP_SOUND           13016
#define IDS_RESCLASS_BP_PLACEABLE       13017
#define IDS_RESCLASS_BP_ITEM            13018
#define IDS_RESCLASS_BP_ENCOUNTER       13019
#define IDS_RESCLASS_BP_DOOR            13020
#define IDS_RESCLASS_BP_CREATURE        13021
#define IDS_RESCLASS_BP_MERCHANT        13022
#define IDS_RESCLASS_SOUND_SET          13023
#define IDS_RESCLASS_GRAPHICAL_PALETTE  13024
#define IDS_RESCLASS_MODEL_SERVER       13025
#define IDS_RESCLASS_AREA               13026
#define IDS_RESCLASS_MODULE             13027
#define IDS_RESCLASS_PLOT               13028
#define IDS_RESCLASS_TEXTURE_DDS        13029
#define IDS_RESCLASS_DSCRIPT            13030
#define ID_POPUP_CUSTOMIZE_TOOLBAR      40001
#define ID_RESOURCES_VIEW               40002
#define ID_RESOURCES_VIEWINNEWWINDOW    40003
#define ID_RESOURCES_CLOSEVIEW          40004
#define ID_RESOURCES_CLOSEALLVIEWS      40005
#define ID_FILE_OPENNWN                 40006
#define ID_FILE_OPTIONS                 40007
#define ID_FILE_OPEN_BINARY             40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
