// -*- C++ -*- generated by wxGlade 0.2.3 on Tue Aug 12 16:48:40 2003



#ifndef WXNWNTREASURE_H
#define WXNWNTREASURE_H


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const char* title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainFrame::attributes
    wxMenuBar* menubar;
    wxStatusBar* statusbar;
    wxToolBar* _tb;
    wxTreeCtrl* tree_ctrl_1;
    // end wxGlade
};


#endif // WXNWNTREASURE_H
