// -*- C++ -*- generated by wxGlade 0.2.3 on Tue Aug 12 16:48:40 2003



#ifndef WXNWNTREASURE_H
#define WXNWNTREASURE_H

//! IDs for various widget events.
enum
{
	ID_New,
	ID_Open,
	ID_Save,
};

class NwnTFrame: public wxFrame {
public:
    // begin wxGlade: NwnTFrame::ids
    // end wxGlade

    NwnTFrame(wxWindow* parent, int id, const char* title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: NwnTFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: NwnTFrame::attributes
    wxMenuBar* _mb;
    wxStatusBar* _sb;
    wxToolBar* _tb;
    wxTreeCtrl* _tc1;
    // end wxGlade

    //! Called when the user wants to open a file.
    void OnOpen(wxCommandEvent& event);

private:
	DECLARE_EVENT_TABLE()

};



#endif // WXNWNTREASURE_H
